export const jobs = [
        {
            id:"Heavy Equipment Operator",
            title: "Heavy Equipment Operator",
            location: "Kalimantan Tengah",
            type: "Full-time",
            dept: "Operations",
            posted: "2 days ago",
            description: "Responsible for operating heavy machinery such as excavators, bulldozers, and dump trucks in coal mining operations. Must follow safety protocols and maintain equipment logs.",
        },
        {
            id:"Site Engineer",
            title: "Site Engineer",
            location: "Kalimantan Selatan",
            type: "Full-time",
            dept: "Engineering",
            posted: "3 days ago",
            description: "Oversee technical aspects of mining site operations, prepare engineering reports, and coordinate with project managers to ensure work is completed on schedule and within budget.",
        },
        {
            id:"Safety Officer",
            title: "Safety Officer",
            location: "Kalimantan Timur",
            type: "Full-time",
            dept: "HSE",
            posted: "5 days ago",
            description: "Monitor and enforce health, safety, and environmental standards on site. Conduct risk assessments, safety audits, and lead emergency response planning.",
        },
        {
            id: "Finance Staff",
            title: "Finance Staff",
            location: "Jakarta",
            type: "Full-time",
            dept: "Finance",
            posted: "1 week ago",
            description: "Handle financial reporting, budgeting, and bookkeeping activities. Support monthly closing processes and liaise with external auditors and tax consultants.",
        },
        {
            id:"HR Recruitment",
            title: "HR Recruitment",
            location: "Jakarta",
            type: "Full-time",
            dept: "Human Resources",
            posted: "1 week ago",
            description: "Manage end-to-end recruitment processes including job posting, candidate screening, interviews, and onboarding. Build talent pipelines for operational and corporate roles.",
        },
        {
            id: "Truck Driver",
            title: "Truck Driver",
            location: "Kalimantan Tengah",
            type: "Contract",
            dept: "Operations",
            posted: "3 days ago",
            description: "Transport coal and materials between mining sites and loading points. Must hold a valid SIM B2 license and have experience driving heavy-duty trucks in off-road conditions.",
        },
]